# Generated by Django 3.2.9 on 2021-12-25 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=50, verbose_name='Sujet')),
                ('message', models.TextField(max_length=1000, verbose_name='Message')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('isRed', models.BooleanField(default=False, verbose_name='Lu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
            ],
        ),
    ]
