# Generated by Django 3.2.9 on 2021-11-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateLastPayment',
            field=models.DateField(blank=True, null=True, verbose_name=' Date dernier paiement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='echeance',
            field=models.DateField(blank=True, null=True, verbose_name='Echeance de cotisation'),
        ),
    ]
