# Generated by Django 3.2.9 on 2021-11-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        ('compte', '0002_auto_20211118_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.regime', verbose_name='Regime'),
        ),
    ]
