# Generated by Django 3.2.9 on 2021-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_alter_user_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='utilisateur',
            field=models.CharField(max_length=150, verbose_name='Déclarant'),
        ),
    ]
