# Generated by Django 3.2.9 on 2021-12-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0005_auto_20211217_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='isactive',
            new_name='isActive',
        ),
    ]
