# Generated by Django 3.2.9 on 2021-12-25 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_auto_20211225_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Payement',
        ),
    ]
