# Generated by Django 3.2.9 on 2021-12-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0009_auto_20211229_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Crée le'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='utilisateur',
            field=models.CharField(max_length=150, verbose_name='Enregistrer par'),
        ),
    ]
