# Generated by Django 3.2.9 on 2022-01-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0010_auto_20211229_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='madia/profil/thumbnail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='madia/profil/image'),
        ),
    ]
