# Generated by Django 4.1 on 2022-08-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0011_auto_20220107_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='madia/beneficiair/thumbnail'),
        ),
    ]
